import pavingImage from "@/assets/product-parking.jpg";
import cobblestoneImage from "@/assets/product-cobblestone.jpg";
import flooringImage from "@/assets/product-flooring.jpg";
import benchImage from "@/assets/product-bench.jpg";
import chairImage from "@/assets/product-chair.jpg";

export type SeoLandingPage = {
  slug: string;
  title: string;
  h1: string;
  eyebrow: string;
  description: string;
  location: string;
  service: string;
  image: string;
  keywords: string[];
  highlights: string[];
};

export const SEO_LANDING_PAGES: SeoLandingPage[] = [
  {
    slug: "granite-paving-stone-bangalore",
    title: "Granite Paving Stone Bangalore | SJ Granite Paving Stone",
    h1: "Granite Paving Stone in Bangalore",
    eyebrow: "Bangalore Stone Supply",
    description: "Premium granite paving stone for Bangalore homes, villas, gardens, parking areas, driveways and commercial landscape projects.",
    location: "Bangalore",
    service: "Granite paving stone supply and installation",
    image: pavingImage,
    keywords: ["granite paving stone Bangalore", "granite stone Bangalore", "stone paving stone Bangalore", "paving stone Bangalore", "parking stone Bangalore", "driveway paving stone Bangalore"],
    highlights: ["Anti-slip outdoor paving stone", "Suitable for parking and garden areas", "Wholesale and retail supply since 2013"],
  },
  {
    slug: "granite-paving-stone-mumbai",
    title: "Granite Paving Stone Mumbai | SJ Granite Paving Stone",
    h1: "Granite Paving Stone in Mumbai",
    eyebrow: "Mumbai Stone Projects",
    description: "Natural granite paving stone and outdoor floor stone for Mumbai residential, villa, resort, garden and commercial projects.",
    location: "Mumbai",
    service: "Granite paving stone supply",
    image: pavingImage,
    keywords: ["granite paving stone Mumbai", "granite stone Mumbai", "stone paving stone Mumbai", "natural stone Mumbai", "floor stone Mumbai", "outdoor paving stone Mumbai"],
    highlights: ["Durable natural granite", "Ideal for outdoor and parking use", "Bulk project supply available"],
  },
  {
    slug: "natural-stone-supplier-india",
    title: "Natural Stone Supplier India | SJ Granite Paving Stone",
    h1: "Natural Stone Supplier in India",
    eyebrow: "All India Supply",
    description: "SJ Granite Paving Stone supplies natural stone, granite paving stone, cobblestone, floor stone, wall stone and garden stone furniture across India.",
    location: "India",
    service: "Natural stone supply",
    image: flooringImage,
    keywords: ["natural stone supplier India", "natural stone India", "granite stone supplier India", "stone paving stone India", "paving stones India", "outdoor stone supplier India"],
    highlights: ["Paving, flooring and wall stone options", "Stone furniture for gardens", "Manufacturing, wholesale and retail support"],
  },
  {
    slug: "cobblestone-pavers-bangalore",
    title: "Cobblestone Pavers Bangalore | SJ Granite Paving Stone",
    h1: "Cobblestone Pavers in Bangalore",
    eyebrow: "Cobble Stone Work",
    description: "Natural cobblestone pavers for Bangalore pathways, gardens, resorts, courtyards, villas and landscape designs.",
    location: "Bangalore",
    service: "Cobblestone paver supply",
    image: cobblestoneImage,
    keywords: ["cobblestone pavers Bangalore", "cobble stone Bangalore", "granite stone Bangalore", "granite cobblestone Bangalore", "pathway stone Bangalore"],
    highlights: ["Natural cobble stone texture", "Strong for pathways and courtyards", "Custom color and finish options"],
  },
  {
    slug: "cobblestone-pavers-mumbai",
    title: "Cobblestone Pavers Mumbai | SJ Granite Paving Stone",
    h1: "Cobblestone Pavers in Mumbai",
    eyebrow: "Mumbai Cobblestone",
    description: "Granite cobblestone and cobble pavers for Mumbai garden, driveway, resort, public park and outdoor landscape projects.",
    location: "Mumbai",
    service: "Cobblestone paving supply",
    image: cobblestoneImage,
    keywords: ["cobblestone pavers Mumbai", "cobble stone Mumbai", "granite stone Mumbai", "garden stone Mumbai", "landscape stone Mumbai"],
    highlights: ["Weather-resistant granite cobbles", "Premium landscape finish", "Project quantity supply available"],
  },
  {
    slug: "parking-stone-bangalore",
    title: "Parking Stone Bangalore | SJ Granite Paving Stone",
    h1: "Parking Stone in Bangalore",
    eyebrow: "Driveway & Parking",
    description: "Heavy-duty parking stone and granite paving stone for Bangalore driveways, apartment parking, villas and commercial parking areas.",
    location: "Bangalore",
    service: "Parking stone supply",
    image: pavingImage,
    keywords: ["parking stone Bangalore", "granite stone Bangalore", "stone paving stone Bangalore", "driveway stone Bangalore", "parking pavers Bangalore", "granite parking stone Bangalore"],
    highlights: ["Strong for vehicle movement", "Anti-slip outdoor finish", "Suitable for villas and commercial sites"],
  },
  {
    slug: "parking-stone-mumbai",
    title: "Parking Stone Mumbai | SJ Granite Paving Stone",
    h1: "Parking Stone in Mumbai",
    eyebrow: "Outdoor Parking Stone",
    description: "Granite parking stone and driveway paving stone for Mumbai homes, apartments, hotels, resorts and commercial parking projects.",
    location: "Mumbai",
    service: "Parking stone and driveway pavers",
    image: pavingImage,
    keywords: ["parking stone Mumbai", "granite stone Mumbai", "stone paving stone Mumbai", "driveway pavers Mumbai", "granite parking stone Mumbai", "parking paving stone Mumbai"],
    highlights: ["Long-lasting granite surface", "Clean outdoor paving finish", "Bulk supply for large areas"],
  },
  {
    slug: "floor-stone-bangalore",
    title: "Floor Stone Bangalore | SJ Granite Paving Stone",
    h1: "Outdoor Floor Stone in Bangalore",
    eyebrow: "Natural Floor Stone",
    description: "Natural outdoor floor stone for Bangalore patios, terraces, courtyards, gardens, walkways and premium exterior flooring.",
    location: "Bangalore",
    service: "Outdoor floor stone supply",
    image: flooringImage,
    keywords: ["floor stone Bangalore", "granite stone Bangalore", "outdoor floor stone Bangalore", "natural floor stone Bangalore", "stone flooring Bangalore"],
    highlights: ["Natural stone look", "Good for patios and terrace areas", "Multiple stone finishes available"],
  },
  {
    slug: "floor-stone-mumbai",
    title: "Floor Stone Mumbai | SJ Granite Paving Stone",
    h1: "Outdoor Floor Stone in Mumbai",
    eyebrow: "Exterior Stone Flooring",
    description: "Natural floor stone and outdoor stone flooring for Mumbai gardens, terraces, patios, villas and commercial exterior projects.",
    location: "Mumbai",
    service: "Natural floor stone supply",
    image: flooringImage,
    keywords: ["floor stone Mumbai", "granite stone Mumbai", "stone flooring Mumbai", "outdoor floor stone Mumbai", "natural stone flooring Mumbai"],
    highlights: ["Premium exterior flooring", "Weather-friendly stone surface", "Supply for residential and commercial projects"],
  },
  {
    slug: "garden-stone-furniture-bangalore",
    title: "Garden Stone Furniture Bangalore | SJ Granite Paving Stone",
    h1: "Garden Stone Furniture in Bangalore",
    eyebrow: "Stone Seating",
    description: "Granite stone benches, stone chairs, stone tables and outdoor garden stone furniture for Bangalore homes, parks and resorts.",
    location: "Bangalore",
    service: "Garden stone furniture supply",
    image: benchImage,
    keywords: ["garden stone furniture Bangalore", "stone bench Bangalore", "stone chair Bangalore", "granite bench Bangalore"],
    highlights: ["Granite benches and chairs", "Durable outdoor seating", "Custom garden furniture options"],
  },
  {
    slug: "garden-stone-furniture-mumbai",
    title: "Garden Stone Furniture Mumbai | SJ Granite Paving Stone",
    h1: "Garden Stone Furniture in Mumbai",
    eyebrow: "Outdoor Stone Furniture",
    description: "Outdoor stone benches, stone chairs and granite garden furniture for Mumbai villas, farmhouses, resorts and public garden projects.",
    location: "Mumbai",
    service: "Outdoor stone furniture supply",
    image: chairImage,
    keywords: ["garden stone furniture Mumbai", "stone bench Mumbai", "stone chair Mumbai", "outdoor stone furniture Mumbai"],
    highlights: ["Stone furniture for gardens", "Strong natural granite material", "Suitable for parks, resorts and homes"],
  },
  {
    slug: "wall-stone-bangalore",
    title: "Wall Stone Bangalore | SJ Granite Paving Stone",
    h1: "Wall Stone in Bangalore",
    eyebrow: "Exterior Wall Stone",
    description: "Natural wall stone and outside stone for Bangalore landscape walls, garden walls, boundary walls and exterior design projects.",
    location: "Bangalore",
    service: "Wall stone supply",
    image: cobblestoneImage,
    keywords: ["wall stone Bangalore", "outside stone Bangalore", "natural wall stone Bangalore", "garden wall stone Bangalore"],
    highlights: ["Natural stone wall finish", "Good for landscape and boundary walls", "Outdoor grade material"],
  },
  {
    slug: "wall-stone-mumbai",
    title: "Wall Stone Mumbai | SJ Granite Paving Stone",
    h1: "Wall Stone in Mumbai",
    eyebrow: "Natural Wall Cladding Stone",
    description: "Outside wall stone and natural stone products for Mumbai exterior walls, gardens, villas, resorts and landscape architecture.",
    location: "Mumbai",
    service: "Wall stone and outside stone supply",
    image: cobblestoneImage,
    keywords: ["wall stone Mumbai", "outside stone Mumbai", "natural wall stone Mumbai", "stone wall cladding Mumbai"],
    highlights: ["Natural outdoor stone look", "Useful for walls and garden borders", "Project supply available"],
  },
  {
    slug: "outdoor-stone-karnataka",
    title: "Outdoor Stone Karnataka | SJ Granite Paving Stone",
    h1: "Outdoor Stone in Karnataka",
    eyebrow: "Karnataka Stone Supply",
    description: "Outdoor natural stone, granite paving stone, cobblestone, parking stone and garden furniture for projects across Karnataka.",
    location: "Karnataka",
    service: "Outdoor stone supply",
    image: pavingImage,
    keywords: ["outdoor stone Karnataka", "granite stone Karnataka", "stone paving stone Karnataka", "granite paving stone Karnataka", "natural stone Karnataka", "cobblestone Karnataka"],
    highlights: ["All Karnataka project support", "Paving, parking and garden stone", "Manufacturing and supply experience"],
  },
  {
    slug: "outdoor-stone-maharashtra",
    title: "Outdoor Stone Maharashtra | SJ Granite Paving Stone",
    h1: "Outdoor Stone in Maharashtra",
    eyebrow: "Maharashtra Stone Projects",
    description: "Natural outdoor stone, paving stone, cobblestone pavers, floor stone and garden stone furniture for Maharashtra projects.",
    location: "Maharashtra",
    service: "Outdoor stone products",
    image: flooringImage,
    keywords: ["outdoor stone Maharashtra", "granite stone Maharashtra", "stone paving stone Maharashtra", "paving stone Maharashtra", "natural stone Maharashtra", "cobblestone Maharashtra"],
    highlights: ["Outdoor stone for large projects", "Residential and commercial supply", "Premium granite material"],
  },
  {
    slug: "granite-paving-stone-hyderabad",
    title: "Granite Paving Stone Hyderabad | SJ Granite Paving Stone",
    h1: "Granite Paving Stone in Hyderabad",
    eyebrow: "Hyderabad Paving Stone",
    description: "Granite paving stone, floor stone, cobblestone and parking stone for Hyderabad homes, villas, gardens and commercial sites.",
    location: "Hyderabad",
    service: "Granite paving stone supply",
    image: pavingImage,
    keywords: ["granite paving stone Hyderabad", "granite stone Hyderabad", "stone paving stone Hyderabad", "paving stone Hyderabad", "parking stone Hyderabad", "natural stone Hyderabad"],
    highlights: ["Natural granite paving", "Good for outdoor and parking use", "Bulk supply available"],
  },
  {
    slug: "granite-paving-stone-chennai",
    title: "Granite Paving Stone Chennai | SJ Granite Paving Stone",
    h1: "Granite Paving Stone in Chennai",
    eyebrow: "Chennai Stone Supply",
    description: "Granite paving stone, cobblestone, floor stone and outdoor stone furniture for Chennai residential and commercial landscapes.",
    location: "Chennai",
    service: "Granite paving stone products",
    image: pavingImage,
    keywords: ["granite paving stone Chennai", "granite stone Chennai", "stone paving stone Chennai", "paving stone Chennai", "cobblestone Chennai", "natural stone Chennai"],
    highlights: ["Outdoor granite products", "Paving and garden stone options", "Wholesale and retail support"],
  },
  {
    slug: "granite-paving-stone-pune",
    title: "Granite Paving Stone Pune | SJ Granite Paving Stone",
    h1: "Granite Paving Stone in Pune",
    eyebrow: "Pune Outdoor Stone",
    description: "Natural granite paving stone, parking pavers, floor stone and garden stone products for Pune homes, villas and commercial projects.",
    location: "Pune",
    service: "Paving stone and parking stone supply",
    image: pavingImage,
    keywords: ["granite paving stone Pune", "granite stone Pune", "stone paving stone Pune", "paving stone Pune", "parking stone Pune", "natural stone Pune"],
    highlights: ["Granite for outdoor use", "Parking and driveway stone", "Project quantity supply"],
  },
  {
    slug: "granite-paving-stone-delhi",
    title: "Granite Paving Stone Delhi | SJ Granite Paving Stone",
    h1: "Granite Paving Stone in Delhi",
    eyebrow: "Delhi Stone Projects",
    description: "Granite paving stone, cobblestone pavers, outdoor floor stone and garden stone furniture for Delhi NCR landscape projects.",
    location: "Delhi",
    service: "Granite paving and cobblestone supply",
    image: cobblestoneImage,
    keywords: ["granite paving stone Delhi", "granite stone Delhi", "stone paving stone Delhi", "paving stone Delhi", "cobblestone Delhi", "natural stone Delhi"],
    highlights: ["Outdoor paving solutions", "Cobblestone and floor stone options", "Residential and commercial supply"],
  },
  {
    slug: "natural-stone-for-garden-india",
    title: "Natural Stone for Garden India | SJ Granite Paving Stone",
    h1: "Natural Stone for Garden Projects in India",
    eyebrow: "Garden Stone India",
    description: "Natural stone for gardens, pathways, landscape edges, stone benches, stone chairs, cobblestone and granite paving across India.",
    location: "India",
    service: "Garden natural stone supply",
    image: benchImage,
    keywords: ["natural stone for garden India", "granite stone India", "stone paving stone India", "garden stone India", "stone furniture India", "garden paving stone India"],
    highlights: ["Garden paving and pathways", "Stone benches and seating", "Natural landscape finish"],
  },
];

export const findSeoLandingPage = (slug?: string) =>
  SEO_LANDING_PAGES.find((page) => page.slug === slug);
